require('dotenv').config();

const mongoose = require('mongoose');
const Restaurant = require('./models/Restaurant');

const seedRestaurants = [
    {
        id: 1,
        name: 'Kyoto Garden Sushi',
        cuisine: 'Japanese',
        neighborhood: 'Gardens',
        address: '11 Kloof Nek Road, Gardens, Cape Town, 8001',
        website: 'https://kyotogarden.co.za/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'saffron',
        description: 'Japanese restaurant in Gardens, listed by Cape Tourism.',
        image: '',
        tags: ['Japanese'],
        featured: false,
    },
    {
        id: 2,
        name: 'Haiku Asian Tapas',
        cuisine: 'Asian tapas',
        neighborhood: 'City Centre',
        address: '58 Burg Street, Cape Town, 8000',
        website: 'https://bukhara.com/haiku/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'coral',
        description: 'Asian tapas restaurant in Cape Town city centre, with Chinese, Japanese, and Thai influences.',
        image: '',
        tags: ['Chinese', 'Japanese', 'Thai'],
        featured: false,
    },
    {
        id: 3,
        name: 'The Wok Bar',
        cuisine: 'Asian fusion',
        neighborhood: 'Gardens',
        address: 'Shop 11, Kloof Street Village, Rheede Street, Gardens, Cape Town, 8001',
        website: 'https://www.thewokbar.com/',
        sourceUrl: 'https://www.thewokbar.com/locations/',
        priceRange: 'Price not listed',
        accent: 'jade',
        description: 'Asian-inspired restaurant at Kloof Street Village in Gardens.',
        image: '',
        tags: ['Korean', 'Thai', 'Japanese', 'Chinese'],
        featured: false,
    },
    {
        id: 4,
        name: '1890 House of Sushi',
        cuisine: 'Japanese and Chinese',
        neighborhood: 'Observatory',
        address: '40 Trill Road, Observatory, Cape Town, 7925',
        website: 'https://www.1890housesushi.co.za/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'indigo',
        description: 'Sushi restaurant listed in Observatory by Cape Tourism.',
        image: '',
        tags: ['sushi', 'Japanese', 'Chinese'],
        featured: false,
    },
    {
        id: 5,
        name: 'Tjing Tjing Torii',
        cuisine: 'Japanese',
        neighborhood: 'City Centre',
        address: '165 Longmarket Street, Cape Town, 8001',
        website: 'https://www.tjingtjing.co.za/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'amber',
        description: 'Japanese restaurant and bar on Longmarket Street in the city centre.',
        image: '',
        tags: ['Japanese'],
        featured: false,
    },
    {
        id: 6,
        name: 'Bao Down',
        cuisine: 'Asian fusion',
        neighborhood: 'Green Point',
        address: 'Exhibition Building, 79 Main Road, Green Point, Cape Town, 8005',
        website: 'https://www.baodowncapetown.com/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'red',
        description: 'Asian restaurant listed at the Exhibition Building in Green Point.',
        image: '',
        tags: ['Asian'],
        featured: false,
    },
    {
        id: 7,
        name: 'Dimples Dumpling House',
        cuisine: 'Chinese',
        neighborhood: 'Muizenberg',
        address: '33 Palmer Road, Muizenberg, Cape Town',
        website: 'https://dimplesdumplinghouse.co.za/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'teal',
        description: 'Dumpling restaurant listed on Palmer Road in Muizenberg.',
        image: '',
        tags: ['dumplings', 'Chinese'],
        featured: false,
    },
    {
        id: 8,
        name: 'Salushi',
        cuisine: 'Japanese and Asian',
        neighborhood: 'Claremont',
        address: '6 Cavendish Street, Claremont, Cape Town',
        website: 'https://www.salushi.com/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'lime',
        description: 'Sushi and Asian-style restaurant listed in Claremont.',
        image: '',
        tags: ['sushi', 'Japanese'],
        featured: false,
    },
    {
        id: 9,
        name: 'South China Dim Sum Bar',
        cuisine: 'Chinese',
        neighborhood: 'City Centre',
        address: '289 Long Street, Cape Town, 8001',
        website: '',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'rose',
        description: 'Dim sum restaurant listed on Long Street in the city centre.',
        image: '',
        tags: ['dim sum', 'Chinese'],
        featured: false,
    },
    {
        id: 10,
        name: "Mr Lin's Sushi & Thai",
        cuisine: 'Japanese and Thai',
        neighborhood: 'Observatory',
        address: '109 Lower Main Road, Observatory, Cape Town, 7925',
        website: '',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'orange',
        description: 'Sushi and Thai restaurant listed on Lower Main Road in Observatory.',
        image: '',
        tags: ['sushi', 'Thai'],
        featured: false,
    },
    {
        id: 11,
        name: 'HON Asian Restaurant',
        cuisine: 'Asian',
        neighborhood: 'Woodstock',
        address: '357 Albert Road, Woodstock, Cape Town, 7925',
        website: '',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'crimson',
        description: 'Asian restaurant listed on Albert Road in Woodstock.',
        image: '',
        tags: ['Asian'],
        featured: false,
    },
    {
        id: 12,
        name: 'Noodle Box Kloof Street',
        cuisine: 'Asian noodles',
        neighborhood: 'Gardens',
        address: '50 Kloof Street, Gardens, Cape Town, 8001',
        website: 'https://www.noodlebox.co.za/',
        sourceUrl: 'https://www.capetourism.com/cape-town-asian-restaurants/',
        priceRange: 'Price not listed',
        accent: 'gold',
        description: 'Noodle restaurant listed on Kloof Street in Gardens.',
        image: '',
        tags: ['noodles', 'Asian'],
        featured: false,
    },
];

const seedDatabase = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('MongoDB connected for seeding');

        await Restaurant.deleteMany({});
        const restaurants = await Restaurant.insertMany(seedRestaurants);

        console.log(`${restaurants.length} restaurants seeded successfully`);
        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error.message);
        process.exit(1);
    }
};

seedDatabase();
